version: '3'
services:
  wordpress_db:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: wordpress_data
      MYSQL_ROOT_PASSWORD: edureka
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=edureka --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  wordpress:
    restart: on-failure
    image: wordpress
    links:
    - wordpress_db:mysql
    ports:
    - "8080:80"
    environment:
      WAIT_HOST: mysql:3306
    depends_on:
    - wordpress_db

  phpmyadmin:
    image: corbinu/docker-phpmyadmin
    links:
    - wordpress_db:mysql
    ports:
    - 8081:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: edureka
